/**
 * Registering `pisnip://` with the desktop, and proving it works
 * (docs/terminal-resolved-clicks.md §6). Linux only.
 *
 * This is the one part of terminal-resolved clicking that happens outside pi,
 * once per machine. `scripts/link-register.py` is the same procedure as a
 * standalone script, and was where the following were measured rather than
 * assumed:
 *
 * - **No dependency on xdg-utils.** A `.desktop` file plus a `mimeapps.list`
 *   entry is sufficient; `mimeinfo.cache` is not consulted for a *default*
 *   lookup. `xdg-mime` and `update-desktop-database` are used when present and
 *   skipped when not — neither was installed on a stock container where this
 *   nonetheless worked.
 * - **The Exec path must not be quoted.** The Desktop Entry spec allows it and
 *   GLib parses it, but `xdg-open` reads the line with
 *   `cut -d= -f2- | first_word | which`, so the quotes reach `which` attached
 *   to the path and it fails. Unquoted parses in both.
 * - **`xdg-open`'s scheme lookup is gated behind `has_display`**, so a probe
 *   run without `DISPLAY`/`WAYLAND_DISPLAY` fails in a way that looks exactly
 *   like a broken registration and is not one.
 *
 * The handler is generated here rather than shipped: it has to bake in an
 * interpreter path and stay valid for every future session, and it must agree
 * with `link-server.ts` about where sockets live.
 */
import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { LINK_SCHEME } from "../shared/link-url.js";

const DESKTOP_ID = "pi-snippet-open.desktop";
const MIME = `x-scheme-handler/${LINK_SCHEME}`;

function dataHome(env: NodeJS.ProcessEnv): string {
	return env.XDG_DATA_HOME || join(homedir(), ".local", "share");
}

function configHome(env: NodeJS.ProcessEnv): string {
	return env.XDG_CONFIG_HOME || join(homedir(), ".config");
}

/**
 * Where the handler lives.
 *
 * Deliberately *not* the pi agent directory: the `Exec` line is baked into the
 * desktop entry at install time and has to stay valid for every future
 * session, while `PI_CODING_AGENT_DIR` moves per session (the test suite
 * repoints it on every run). Same reasoning as `settings.ts` keeping
 * preferences out of the session store, one level further out.
 */
export function handlerPath(env: NodeJS.ProcessEnv = process.env): string {
	return join(dataHome(env), "pi-snippet", "open-handler");
}

export function desktopPath(env: NodeJS.ProcessEnv = process.env): string {
	return join(dataHome(env), "applications", DESKTOP_ID);
}

export function mimeappsPath(env: NodeJS.ProcessEnv = process.env): string {
	return join(configHome(env), "mimeapps.list");
}

/**
 * The handler, as a python3 script.
 *
 * python3 because it is the most reliably present interpreter that can speak
 * AF_UNIX from a bare `exec` — a POSIX shell cannot, and pi's own executable is
 * not necessarily a node CLI (under the snap `process.execPath` is the pi
 * binary). It is stateless: the socket comes from the token in the URL, so this
 * file is written once and serves every session that follows.
 *
 * The directory list must match `socketDirCandidates()` in `link-server.ts`,
 * in the same order — these two processes may not share a namespace, and this
 * list is the whole of their agreement about where to meet.
 */
export function handlerSource(): string {
	return `#!/usr/bin/env python3
"""pi-snippet click handler. Forwards one ${LINK_SCHEME}:// URL and exits.

Generated by pi-snippet; edits are lost on the next install. Carries no text:
the URL names a slot, and the pi session decides what that slot means.
"""
import os, socket, sys, tempfile, urllib.parse

u = urllib.parse.urlparse(sys.argv[1] if len(sys.argv) > 1 else "")
if u.scheme != "${LINK_SCHEME}" or not u.netloc.isalnum():
    sys.exit(2)

def candidates():
    explicit = os.environ.get("PI_SNIPPET_SOCKET_DIR")
    if explicit:
        yield explicit
    runtime = os.environ.get("XDG_RUNTIME_DIR")
    if runtime:
        yield os.path.join(runtime, "pi-snippet")
    yield os.path.join(tempfile.gettempdir(), "pi-snippet-%d" % os.getuid())

for directory in candidates():
    path = os.path.join(directory, u.netloc + ".sock")
    try:
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.settimeout(2)
        s.connect(path)
        s.sendall((u.path.strip("/") + "\\n").encode())
        s.close()
        sys.exit(0)
    except OSError:
        continue

# No live session at any candidate. Normal for a chip clicked in old
# scrollback, so fail quietly rather than showing the user an error.
sys.exit(1)
`;
}

export interface InstallResult {
	ok: boolean;
	handler: string;
	desktop: string;
	mimeapps: string;
	warnings: string[];
}

export function install(env: NodeJS.ProcessEnv = process.env): InstallResult {
	const handler = handlerPath(env);
	const desktop = desktopPath(env);
	const warnings: string[] = [];

	mkdirSync(dirname(handler), { recursive: true });
	writeFileSync(handler, handlerSource(), "utf8");
	chmodSync(handler, 0o755);

	// Unquoted on purpose — see the header. The cost is that a path containing
	// a space cannot be expressed in a way xdg-open will parse, so say so
	// rather than installing something that silently only half works.
	if (handler.includes(" ")) {
		warnings.push(
			`${handler} contains a space; xdg-open cannot parse its Exec line (the portal and gio still can)`,
		);
	}

	mkdirSync(dirname(desktop), { recursive: true });
	writeFileSync(
		desktop,
		[
			"[Desktop Entry]",
			"Type=Application",
			"Name=pi-snippet click handler",
			"Comment=Inserts a suggestion into the pi session that painted it",
			`Exec=${handler} %u`,
			"Terminal=false",
			"NoDisplay=true",
			`MimeType=${MIME};`,
			"",
		].join("\n"),
		"utf8",
	);

	if (!run("update-desktop-database", [dirname(desktop)])) {
		warnings.push("update-desktop-database not run (absent); the default association still applies");
	}
	if (!run("xdg-mime", ["default", DESKTOP_ID, MIME])) {
		setDefaultByHand(env);
	}

	return { ok: true, handler, desktop, mimeapps: mimeappsPath(env), warnings };
}

export function uninstall(env: NodeJS.ProcessEnv = process.env): void {
	for (const path of [desktopPath(env), handlerPath(env)]) {
		try {
			if (existsSync(path)) unlinkSync(path);
		} catch {
			/* nothing we can do, and not worth failing the toggle over */
		}
	}
	const path = mimeappsPath(env);
	try {
		if (existsSync(path)) {
			const kept = readFileSync(path, "utf8")
				.split("\n")
				.filter((line) => !line.startsWith(`${MIME}=`));
			writeFileSync(path, kept.join("\n"), "utf8");
		}
	} catch {
		/* the association is stale but harmless once the desktop file is gone */
	}
	run("update-desktop-database", [dirname(desktopPath(env))]);
}

export function isInstalled(env: NodeJS.ProcessEnv = process.env): boolean {
	return existsSync(handlerPath(env)) && existsSync(desktopPath(env));
}

/**
 * Add the default association without xdg-utils, preserving everything else in
 * the file. `mimeapps.list` is a plain ini and this is the only key we own.
 */
export function setDefaultByHand(env: NodeJS.ProcessEnv = process.env): void {
	const path = mimeappsPath(env);
	const entry = `${MIME}=${DESKTOP_ID}`;
	let lines: string[] = [];
	try {
		if (existsSync(path)) lines = readFileSync(path, "utf8").split("\n");
	} catch {
		lines = [];
	}
	lines = lines.filter((line) => !line.startsWith(`${MIME}=`));
	const header = lines.findIndex((line) => line.trim() === "[Default Applications]");
	if (header === -1) lines.push("[Default Applications]", entry, "");
	else lines.splice(header + 1, 0, entry);
	try {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, lines.join("\n"), "utf8");
	} catch {
		/* an unwritable config dir costs link mode, not the session */
	}
}

/** Run a helper if it exists. False means "not available", never "it failed". */
function run(command: string, args: string[]): boolean {
	try {
		execFileSync(command, args, { stdio: "ignore", timeout: 10_000 });
		return true;
	} catch (error) {
		const code = (error as NodeJS.ErrnoException).code;
		return code !== "ENOENT";
	}
}

/**
 * The openers a probe should try, nearest-to-Ghostty first: its GTK apprt calls
 * the XDG portal with `ask=false` and only falls back to `xdg-open` when the
 * portal errors.
 */
export function probeCommands(url: string): Array<{ command: string; args: string[] }> {
	return [
		{
			command: "gdbus",
			args: [
				"call", "-e",
				"-d", "org.freedesktop.portal.Desktop",
				"-o", "/org/freedesktop/portal/desktop",
				"-m", "org.freedesktop.portal.OpenURI.OpenURI",
				"", url, "{'ask': <false>}",
			],
		},
		{ command: "gio", args: ["open", url] },
		{ command: "xdg-open", args: [url] },
	];
}

/**
 * Fire a URL at each opener in turn and stop at the first that arrives.
 *
 * The caller supplies `arrived` — in practice a promise resolved by the live
 * `LinkServer`, so the probe exercises the real socket rather than a stand-in.
 */
export async function probe(
	url: string,
	arrived: () => Promise<boolean>,
): Promise<{ opener: string | null; tried: string[] }> {
	const tried: string[] = [];
	for (const { command, args } of probeCommands(url)) {
		try {
			execFileSync(command, args, { stdio: "ignore", timeout: 10_000 });
		} catch (error) {
			const code = (error as NodeJS.ErrnoException).code;
			tried.push(code === "ENOENT" ? `${command} (absent)` : `${command} (failed)`);
			continue;
		}
		if (await arrived()) return { opener: command, tried };
		tried.push(`${command} (no round trip)`);
	}
	return { opener: null, tried };
}
