#!/usr/bin/env python3
"""Terminal-resolved clicking over real SSH, in two containers. Run this one.

    sudo bash scripts/docker-ssh-env.sh     # once: build the two hosts
    sudo python3 scripts/ssh-click-docker.py

Ensures the client has the handler `link-install.ts` generates — installed by
calling the extension's own `install()`, so what fires the click is the script
that ships, not a copy — then runs scripts/ssh-click-client.py inside the client
container and relays its verdict.

Rebuild first: the containers mount this repo and load dist/, not the sources.
"""
import os, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT = "pisnip-client"
SERVER = "pisnip-server"
DIST = os.path.join(ROOT, "dist", "extension", "pi-snippet-tui.js")

INSTALLER = """
import { install, isInstalled } from "%s/src/extension/link-install.js";
const r = install();
console.log(JSON.stringify({ ...r, isInstalled: isInstalled() }));
""" % ROOT


def run(*args, **kw):
	return subprocess.run(args, capture_output=True, text=True, **kw)


def die(message):
	print(message, file=sys.stderr)
	sys.exit(1)


if not os.path.exists(DIST):
	die("dist/extension/pi-snippet-tui.js is missing — run `npm run build` first")

for name in (SERVER, CLIENT):
	if run("docker", "inspect", "-f", "{{.State.Running}}", name).stdout.strip() != "true":
		die(f"{name} is not running — run: sudo bash scripts/docker-ssh-env.sh")

# The handler, generated by the extension's own installer.
tmp = tempfile.mkdtemp(prefix="pisnip-installer-")
try:
	src = os.path.join(tmp, "install-handler.ts")
	out = os.path.join(tmp, "install-handler.js")
	with open(src, "w") as fh:
		fh.write(INSTALLER)
	build = run(os.path.join(ROOT, "node_modules", ".bin", "esbuild"), src,
	            "--bundle", "--platform=node", "--format=esm", f"--outfile={out}")
	if build.returncode != 0:
		die("could not bundle the installer:\n" + build.stderr)
	if run("docker", "cp", out, f"{CLIENT}:/tmp/install-handler.js").returncode != 0:
		die("could not copy the installer into the client")
	installed = run("docker", "exec", "-u", "dev", CLIENT, "node", "/tmp/install-handler.js")
	if installed.returncode != 0:
		die("handler install failed:\n" + installed.stderr)
	print("client handler:", installed.stdout.strip())
finally:
	shutil.rmtree(tmp, ignore_errors=True)

driver = os.path.join(ROOT, "scripts", "ssh-click-client.py")
if run("docker", "cp", driver, f"{CLIENT}:/tmp/ssh-click-client.py").returncode != 0:
	die("could not copy the driver into the client")

print(f"--- driving real pi on {SERVER} from {CLIENT} ---", flush=True)
result = subprocess.run(
	["docker", "exec", "-u", "dev", CLIENT, "python3", "/tmp/ssh-click-client.py"])
sys.exit(result.returncode)
